In [2]:
!pip install ucimlrepo

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ucimlrepo in c:\users\tanma\appdata\roaming\python\python311\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in d:\programdata\anaconda3\lib\site-packages (from ucimlrepo) (2.0.3)
Requirement already satisfied: certifi>=2020.12.5 in d:\programdata\anaconda3\lib\site-packages (from ucimlrepo) (2023.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\programdata\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\programdata\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\programdata\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in d:\programdata\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.24.3)
Requirement already satisfied: six>=1.5 in d:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
wine_quality = fetch_ucirepo(id=186) 
  
# data (as pandas dataframes) 
X = wine_quality.data.features 
y = wine_quality.data.targets

In [4]:
X

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8

In [5]:
y

      quality
0           5
1           5
2           5
3           6
4           5
...       ...
6492        6
6493        5
6494        6
6495        7
6496        6

[6497 rows x 1 columns]

In [6]:
import pandas as pd
df = pd.concat([X, y],axis=1, join='outer')

In [7]:
df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split  
train,test=train_test_split(df)
x_train = train.drop(['quality'],axis=1)
x_test = test.drop(['quality'],axis=1)

y_train = train['quality']
y_test = test['quality']
# Model training
# lr = ElasticNet()
# lr.fit(x_train,y_train)
# pred = lr.predict(x_test)
rf=RandomForestClassifier(n_estimators=250,max_depth=20)
rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=20, n_estimators=250)

In [40]:
prob_pred = rf.predict_proba(x_test)

In [41]:
print(prob_pred[0])

[0.00000000e+00 4.00000000e-03 5.01943648e-02 9.41348492e-01
 4.22857143e-03 2.28571429e-04 0.00000000e+00]

In [42]:
prob_pred.shape

(1625, 7)

In [43]:
y_test

5557    6
5271    8
733     5
1149    6
5895    6
       ..
10      5
5927    5
670     5
4709    6
3784    7
Name: quality, Length: 1625, dtype: int64

In [44]:
import numpy as np
y_test_np = np.array(y_test)

In [45]:
y_test_np.shape

(1625,)

In [46]:
from sklearn.metrics import roc_auc_score
prob_pred = rf.predict_proba(x_test)
roc = roc_auc_score(y_test,prob_pred,multi_class='ovr')

In [47]:
roc

0.8879740285772658